events {
    worker_connections 1024;
}

http {
    
    upstream auth_servers {
        server signing:8003;
    }

    upstream management_servers {
        server device_mgmt:8001;
    }

    upstream monitoring_servers {
        ip_hash; 
        server monitoring:8002;
    }

    server {
        listen 80;

        # 1. Dashboard (Monitoring) sur la racine
        # Attention: Votre Frontend React tourne separement sur le port 5173.
        # Ici on redirige vers l'API Monitoring comme demande.
        location / {
            proxy_pass http://monitoring_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Service d'Authentification
        # Redirection: /auth/ -> /users/ (car votre API est prefixee par /users)
        location /auth/ {
            proxy_pass http://auth_servers/users/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 3. Gestion des Devices
        location /devices {
            proxy_pass http://management_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 4. API de Monitoring
        # Redirection: /api/monitoring/ -> /monitoring/ (car votre API est prefixee par /monitoring)
        location /api/monitoring/ {
            proxy_pass http://monitoring_servers/monitoring/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 5. Support des WebSockets (Socket.io)
        location /socket.io/ {
            proxy_pass http://monitoring_servers/socket.io/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}
